export const environment = {
  // baseUrl: "https://api.nubyira.com/api/v1",
  baseUrl: "https://stage-backend.nubyira.com/api/v1",
  imageUrl: "https://stage-backend.nubyira.com",
  registerUrl: "/register/",
  loginUrl: "/login/",
  verifyEmail: "/verify-email/",
  resentOtp: "/resend-otp/",
  forgotPassword: "/forgot-password/",
  setPassword: "accounts/auth/set-new-password",
  courses: "/courses/",
  resendVerificationLink: "/resend-confirmation-link/",
  paymentVerification: "/subscription/paystack/verify/",
  webinarVerication: "/course/payment/verify/",
};
